### ISSUE TITLE
Difficulty compiling pcp

### ISSUE THREAD

**Issue by Skim45** [performancecopilot/pcp#1661]
I'm trying to [cross compile pcp for windows](https://github.com/performancecopilot/pcp/blob/main/INSTALL.md) (under Fedora), using `./Makepkgs --verbose --target mingw64` but i'm getting the following error:

```bash
/usr/x86_64-w64-mingw32/sys-root/mingw/include/minwindef.h:140:26: note: previous declaration of 'WORD' with type 'WORD' {aka 'short unsigned int'}
  140 |   typedef unsigned short WORD;
      |                          ^~~~
labels.c: In function 'local_user_labels':
labels.c:1263:35: warning: implicit declaration of function 'getgid'; did you mean 'getpid'? [-Wimplicit-function-declaration]
 1263 |                     (unsigned int)getgid(), (unsigned int)getuid());
      |                                   ^~~~~~
      |                                   getpid
labels.c:1263:59: warning: implicit declaration of function 'getuid'; did you mean 'getpid'? [-Wimplicit-function-declaration]
 1263 |                     (unsigned int)getgid(), (unsigned int)getuid());
      |                                                           ^~~~~~
      |                                                           getpid
make[3]: *** [<builtin>: labels.o] Error 1
make[2]: *** [GNUmakefile:22: default] Error 2
make[1]: *** [GNUmakefile:146: default_pcp] Error 2
make[1]: Leaving directory '/root/pcp/pcp-6.0.0/src'
make: *** [GNUmakefile:49: default_pcp] Error 2
```

I'm also having difficulty compiling for other than `mingw` using `./Makepkgs --verbose`, I am getting the following:

```bash
Project ERROR: Unknown module(s) in QT: svg
make[5]: Makefile: No such file or directory
make[5]: *** No rule to make target 'Makefile'.  Stop.
make[4]: *** [GNUmakefile:13: build-me] Error 2
make[3]: *** [GNUmakefile:21: default] Error 2
make[2]: *** [GNUmakefile:146: default_pcp] Error 2
make[2]: Leaving directory '/root/pcp/pcp-6.0.0/pcp-6.0.0/src'
make[1]: *** [GNUmakefile:49: default_pcp] Error 2
make[1]: Leaving directory '/root/pcp/pcp-6.0.0/pcp-6.0.0'
error: Bad exit status from /var/tmp/rpm-tmp.OyQmMM (%build)
```

I have the `qt5-qtsvg-devel` package installed so shouldn't face the above, but I'm running out of things to try, any ideas on how solve this?

**Comment by natoscott** [comment]
@Skim45 thanks for the report - looks like an un-guarded use of the getuid/getgid APIs has entered some relatively new code.
The Qt SVG issue is unrelated though.  I don't see that failure (on f36) so I guess you're missing the mingw64-qt5-qtsvg package.

**Comment by natoscott** [comment]
| [...] for other than mingw using ./Makepkgs --verbose

I misread the above - for a native Fedora build you will need the qt5-qtsvg-devel package.

Looking into Windows cross-compile a little further - there's a few little problems here and there but eventually the build reaches deps/hiredis-cluster/hiutil.c in libpcp_web (the hiredis part is OK, its the newer clustering code that needs some love) ... resolving that is going to take more time than I have available at the moment.

I'll push what I have into a branch in case its useful to you - perhaps this is something you and I can look into further together, after next weeks 6.0 release.

**Comment by Skim45** [comment]
@natoscott, thank you so much for looking at it. I'll pick up from where you left 👍

**Comment by GKSONG** [comment]
Hello  Nathan

I've stopped on "libc-config.h" (Windows, git-sdk & mingw64 env. isn't have this file)
I've tried install <glibc and lib32-glibc> through several ways, but failed.
 ** pacman -dU glibc-2.35-6-x86_64.pkg.tar.zst  ... (conflict issues)
 ** source compile .. (not support platform)

Could you advise the easiest way to setup glibc env. ?

**Comment by natoscott** [comment]
@GKSONG we don't want to involve glibc setup here, I've resolved that compilation issue in my windows-cross-compile branch now.  I've got a fix for the hiredis-cluster build issue as well, will discuss that with the maintainers of that project separately though.

Getting there...

**Comment by GKSONG** [comment]
Hello Nathan

Thanks for your comment.
In your commit code "fnmatch.c", I found "fnmatch_loop.c" is called.
But "fnmatch_loop.c" isn't existed on PCP repository.
So I've checked gnu c library on (https://github.com/coreutils/gnulib/)
Without install gnu c library, "libpcp_web" library can't build.

Anyway thanks.

**Comment by natoscott** [comment]
@GKSONG @Skim45 try 'main' branch now, things are much improved and >99% of PCP is compiling once more with MinGW64, including all the GUI tools.

The one remaining thing I know of is the src/find-filter code which seems to be encountering confusion related to stat(2) fields.
Let me know how you guys fare now & we could look into this further.  Another aspect I've not looked into is compilation with libuv (used by pmproxy, pmseries, pmsearch and related code) - there's no Fedora cross-compile package for this it seems.

To really get the Windows port back on its feet for good and in the hands of users, we'd need two other things: CI (github actions) and packaging (we'd need to select an OSS Windows packaging technology that supports all our needs).  Does anyone have interest in working on these aspects?

**Comment by GKSONG** [comment]
Thanks @natoscott 

I am building pcp-5.3.7 code because linux(centos and ubuntu) version works on 5.3.7.
To resolve "fnmatch.c" related issue, I did the following action and passed build stage.
   -- copy (/usr/include/fnmatch.h) to licpcp_web/src  directory
   -- changet to <fnmatch.h> to "fnmatch.h"
   -- add library "-lgettextlib"

Now I am on pmproxy build and refer to your latest code.
I will share everything (problem and resolution) with you after completing tests.

**Comment by natoscott** [comment]
@GKSONG there's no longer any fnmatch issue in latest main branch - you should be able to build directly with the code there now, no workarounds.

**Comment by GKSONG** [comment]
Thanks @natoscott 

I am struggling with **"perl --> LogImport"** module because of the following message.

~~~~~~~~~
gcc  -c  -IC:/3RD_SW/git-sdk-64/pcp/pcp-5.3.7/src/include/pcp -I/usr/include/pcp -I\include\pcp -I\c\include -DWIN32 -DWIN64 -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fno-strict-aliasing -mms-bitfields -g   -DVERSION=\"1.02\" -DXS_VERSION=\"1.02\"  "-IC:\3RD_SW\git-sdk-64\mingw64\lib\perl5\core_perl\CORE"  -DPERLIO_NOT_STDIO=0 -DPCP_VERSION LogImport.c
In file included from LogImport.xs:2:
C:\3RD_SW\git-sdk-64\mingw64\lib\perl5\core_perl\CORE/perl.h:3566:59: error: expected ')' before '*' token
 3566 | #    define PERL_GET_THX     ((PerlInterpreter *)PERL_GET_CONTEXT)
...
...
C:\3RD_SW\git-sdk-64\mingw64\lib\perl5\core_perl\CORE/iperlsys.h:1073:18: note: in definition of macro 'PerlProc_sleep'
 1073 |         (*PL_Proc->pSleep)(PL_Proc, (t))
      |                  ^~
~~~~~~~~~

So I modified GNUmakefile to skip "perl". ( pmie, pmiestatus, htop also skipped)

Finally tar file was created and copy to specific location (PCP_DIR --> PCP_DIR=C:\3RD_SW\git-sdk-64\mingw64) . The basic checking was done like "pmcd --help" but doing tar isn't fully done. (ex. /usr/bin/tar: var/lib/pcp/config/derived/cpu-util.conf: Cannot stat: No such file or directory ....)

It's try to start "pmcd.exe"

**Comment by GKSONG** [comment]
@natoscott

May I request your advise for running "pmcd.exe" ?

o. Current situation
   - PCP_DIR=C:\3RD_SW\git-sdk-64\mingw64
   - add to the system PATH ( based on Install.md)
   - On windows CMD terminal, when I type "pmcd.exe" the following "pmcd.log" is generated.
   ~~~~~~~~~~~~~~~~~
C:\3RD_SW\git-sdk-64\mingw64>type pmcd.log
_Log for pmcd on DESKTOP-765NDQ5 started Sun Sep 11 16:46:17 2022

Error Parsing ASCII PMNS: Cannot open "/var/lib/pcp/pmns/root" <----- ?????
Error: pmLoadASCIINameSpace(DEFAULT, 1): No such file or directory
[Sun Sep 11 16:46:17] pmcd(11024) Error: pmcd not started due to errors!

Log finished Sun Sep 11 16:46:17 2022__
   ~~~~~~~~~~~~~~~~~
   _(workaround) cp /mingw64/var/lib/pcp/pmdas/windows/root /mingw64/var/lib/pcp/pmns/._

Q1) Makepkgs (285 line) : is correct ?
      _configopts="--sysconfdir=/etc --localstatedir=/var --prefix=/mingw64"_

Q2) /etc/pcp.conf  (C:\3RD_SW\git-sdk-64\mingw64\etc\pcp.conf) : Can I get the sample for Windows ?
     _PCP_ETC_DIR=/etc
     PCP_SYSCONF_DIR=/etc/pcp
     ...
    PCP_BIN_DIR=/mingw64/bin
    PCP_BINADM_DIR=/mingw64/libexec/pcp/bin
    ..
    PCP_PMCDCONF_PATH=/etc/pcp/pmcd/pmcd.conf_

    Do I need to change the real path (ex. C:\3RD_SW\git-sdk-64\mingw64\etc\pmcd\pmcd.conf) ?

Q3) /etc/pmcd/pmcd.conf : Should be changed ?
     -- File/cmd column : /var/lib/pcp/pmdas/pmcd/pmda_pmcd.dll  <-- path incorrect.
         (correct path : ./libexec/pcp/pmdas/pmcd/pmda_pmcd.dll or
                                ./var/lib/pcp/pmdas/pmcd/pmda_pmcd.dll )
     -- How to describe path name ?
         (option-1) /var/lib/pcp/pmdas/pmcd/pmda_pmcd.dll
         (option-2) C:\3RD_SW\git-sdk-64\mingw64\var\lib\pcp\pmda\pmcd\pmda_pmcd.dll
         (option-3) ${PCP_DIR}/var/lib/pcp/pmda/pmcd/pmda_pmcd.dll

      -- Why "pmdaroot" record isn't created like linux ?
          /var/lib/pcp/pmdas/root/pmdaroot (File/cmd column)

Q4) PCP files layout is same to linux ?
      _(ex) https://installati.one/amazonlinux/2/pcp.x86_64/_

Q5) Can I get the following file ?
      _-- Makepkgs
      -- pcp/pcp-{version}/build/*tar.gz  <--- If you built pcp for Windows._
 
Q6) In "tar" staging, the file location isn't correct so warning message happens.
      -- log 
          /usr/bin/tar: **var/lib/pcp/config/pmieconf/cpu/**context_switch: Cannot stat: No such file or directory
      -- my environment
          **/mingw64/etc/pcp/pmieconf/cpu/**

Thanks

**Comment by natoscott** [comment]
| May I request your advise for running "pmcd.exe" ?

Sure.  It may be easier if we chat directly though?  If you'd like to, please join the PCP slack where we could discuss in the #windows channel.  Details here:  https://pcp.io/community.html

Couple of hints though - in general we don't run the pmcd binary directly, a front-end script .../libexec/pcp/lib/pmcd does this to ensure (some of) the problems you encountered don't happen.  In particular, it ensures the namespace is ready.

Regarding paths, in general we've used PCP_DIR in the past - it was originally introduced on Windows to allow for arbitrary installation locations - and that setting comes in from the registry, everywhere else within PCP we use paths relative to PCP_DIR.

**Comment by natoscott** [comment]
I'm going to close this as the original problem report and many of the followups are resolved and fixes merged now.

Much work remains to get a fully packaged-for-Windows version of PCP beyond the first build though.  If you'd like to help as either a developer, tester or end user please do join @GKSONG and myself in the #windows channel of PCP slack.  [ pcp.io/community.html for slack details ]

cheers.
